//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYSimpleAcc {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZYSimpleAcc.ResourcesEnglish", typeof(ResourcesEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid License.
        /// </summary>
        internal static string activationneeded {
            get {
                return ResourceManager.GetString("activationneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Accounting System.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V 1.0.0.0.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPeration Canceled By User.
        /// </summary>
        internal static string CancelByUser {
            get {
                return ResourceManager.GetString("CancelByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleAcc2021.
        /// </summary>
        internal static string dbnamecon {
            get {
                return ResourceManager.GetString("dbnamecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        internal static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plesae Type Digits Only.
        /// </summary>
        internal static string digitOnlyError {
            get {
                return ResourceManager.GetString("digitOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Fill The Required Fields.
        /// </summary>
        internal static string emptyFields {
            get {
                return ResourceManager.GetString("emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Already Exist.
        /// </summary>
        internal static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Will Exit ? Sure ? .
        /// </summary>
        internal static string ExitPromt {
            get {
                return ResourceManager.GetString("ExitPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username Or Passowrd - User Inactive.
        /// </summary>
        internal static string FaieldLogin {
            get {
                return ResourceManager.GetString("FaieldLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        internal static string invalidData {
            get {
                return ResourceManager.GetString("invalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password Invalid.
        /// </summary>
        internal static string invalidPassword {
            get {
                return ResourceManager.GetString("invalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string JordanCleaningVersion {
            get {
                return ResourceManager.GetString("JordanCleaningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Technologies Solutions © 2021.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Technologies Solutions - Attention.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Text boxes.
        /// </summary>
        internal static string missingTextboxes {
            get {
                return ResourceManager.GetString("missingTextboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select .
        /// </summary>
        internal static string Noselection {
            get {
                return ResourceManager.GetString("Noselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not Exist.
        /// </summary>
        internal static string notExist {
            get {
                return ResourceManager.GetString("notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zy@admin2021.
        /// </summary>
        internal static string passwordcon {
            get {
                return ResourceManager.GetString("passwordcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plesae Activate App.
        /// </summary>
        internal static string pleaseActive {
            get {
                return ResourceManager.GetString("pleaseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZUBAIDI.
        /// </summary>
        internal static string servercon {
            get {
                return ResourceManager.GetString("servercon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Happened - Try Again .
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Is used by Another - Can&apos;t be deleted  .
        /// </summary>
        internal static string uesd {
            get {
                return ResourceManager.GetString("uesd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string usernamecon {
            get {
                return ResourceManager.GetString("usernamecon", resourceCulture);
            }
        }
    }
}
