//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZYSimpleAcc.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZYSimpleAcc.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرخصة غير صحيحة.
        /// </summary>
        internal static string activationneeded {
            get {
                return ResourceManager.GetString("activationneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الاضافة بنجاح.
        /// </summary>
        internal static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا السند ملغى سابقا.
        /// </summary>
        internal static string AlreadyCancelled {
            get {
                return ResourceManager.GetString("AlreadyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Accounting System.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام محاسبة زد واي.
        /// </summary>
        internal static string AppNameAr {
            get {
                return ResourceManager.GetString("AppNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V 1.0.0.0.
        /// </summary>
        internal static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء النسخة الإحتياطية.
        /// </summary>
        internal static string BackUpCreated {
            get {
                return ResourceManager.GetString("BackUpCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء العملية الاخيرة من قبل المستخدم.
        /// </summary>
        internal static string CancelByUser {
            get {
                return ResourceManager.GetString("CancelByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء السند بنجاح.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت المعالجة.
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleAcc2021.
        /// </summary>
        internal static string dbnamecon {
            get {
                return ResourceManager.GetString("dbnamecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح.
        /// </summary>
        internal static string deleted {
            get {
                return ResourceManager.GetString("deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال أرقام فقط.
        /// </summary>
        internal static string digitOnlyError {
            get {
                return ResourceManager.GetString("digitOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء ادخال المعلومات المطلوبة.
        /// </summary>
        internal static string emptyFields {
            get {
                return ResourceManager.GetString("emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى الانتباه ان السعر فارغ .
        /// </summary>
        internal static string emptyPrice {
            get {
                return ResourceManager.GetString("emptyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر موجود مسبقا.
        /// </summary>
        internal static string Exist {
            get {
                return ResourceManager.GetString("Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم اغلاق النظام - هل أنت متأكد ؟ .
        /// </summary>
        internal static string ExitPromt {
            get {
                return ResourceManager.GetString("ExitPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اسم المستخدم أو كلمة المرور - أو المستخدم غير فعال.
        /// </summary>
        internal static string FaieldLogin {
            get {
                return ResourceManager.GetString("FaieldLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات السند غير مكتملة.
        /// </summary>
        internal static string InfoOfStoreinnotEntered {
            get {
                return ResourceManager.GetString("InfoOfStoreinnotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إخال المعلومات بشكل صحيح.
        /// </summary>
        internal static string invalidData {
            get {
                return ResourceManager.GetString("invalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور الحالية خاطئة.
        /// </summary>
        internal static string invalidPassword {
            get {
                return ResourceManager.GetString("invalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المادة مدخلة من قبل.
        /// </summary>
        internal static string itemInEnteredGrid {
            get {
                return ResourceManager.GetString("itemInEnteredGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20.
        /// </summary>
        internal static string JordanCleaningVersion {
            get {
                return ResourceManager.GetString("JordanCleaningVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Technologies Solutions © 2021.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زد واي لحلول تكنولوجيا المعلومات © 2021 .
        /// </summary>
        internal static string LogoAR {
            get {
                return ResourceManager.GetString("LogoAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZY Technologies Solutions - تنبيه.
        /// </summary>
        internal static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء تعبأة المعلومات المطلوبة.
        /// </summary>
        internal static string missingTextboxes {
            get {
                return ResourceManager.GetString("missingTextboxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات - نتائج بحث.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الجدول غير مكتملة.
        /// </summary>
        internal static string noDataEnterinGrid {
            get {
                return ResourceManager.GetString("noDataEnterinGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات للإدخال.
        /// </summary>
        internal static string noDatatoEnterToGrid {
            get {
                return ResourceManager.GetString("noDatatoEnterToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات للحذف.
        /// </summary>
        internal static string norowstodelete {
            get {
                return ResourceManager.GetString("norowstodelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إلأختيار.
        /// </summary>
        internal static string Noselection {
            get {
                return ResourceManager.GetString("Noselection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر غير موجود.
        /// </summary>
        internal static string notExist {
            get {
                return ResourceManager.GetString("notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zy@admin2021.
        /// </summary>
        internal static string passwordcon {
            get {
                return ResourceManager.GetString("passwordcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء تفعيل النظام.
        /// </summary>
        internal static string pleaseActive {
            get {
                return ResourceManager.GetString("pleaseActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الصيانة.
        /// </summary>
        internal static string ProccessCompleted {
            get {
                return ResourceManager.GetString("ProccessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال الكمية.
        /// </summary>
        internal static string qtyRequired {
            get {
                return ResourceManager.GetString("qtyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MZUBAIDI.
        /// </summary>
        internal static string servercon {
            get {
                return ResourceManager.GetString("servercon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ - حاول مرة أخرى.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا العنصر مستخدم لا يمكن حذفه.
        /// </summary>
        internal static string uesd {
            get {
                return ResourceManager.GetString("uesd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديث بنجاح.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيتم تحديث المعلومات ؟ .
        /// </summary>
        internal static string updatePrompt {
            get {
                return ResourceManager.GetString("updatePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        internal static string usernamecon {
            get {
                return ResourceManager.GetString("usernamecon", resourceCulture);
            }
        }
    }
}
